# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ujwalgowda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: portfolio
service: portfolio-backend

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: index.app
    events:
      - http:
          path: /
          method: get
      - http:
          path: /contact
          method: post
